// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxoUVQoN0-bwNQ77Za2SxXJivmBmmgtxM',
    appId: '1:417667239161:web:9e28b6aadc00aeff55e628',
    messagingSenderId: '417667239161',
    projectId: 'project-f7aa0',
    authDomain: 'project-f7aa0.firebaseapp.com',
    databaseURL: 'https://project-f7aa0-default-rtdb.firebaseio.com',
    storageBucket: 'project-f7aa0.appspot.com',
    measurementId: 'G-74MTJBLEGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmpMiBEPNL1iwg9yro6M5VOyPhKn1oMqM',
    appId: '1:417667239161:android:1dfb7f61c8d58f9e55e628',
    messagingSenderId: '417667239161',
    projectId: 'project-f7aa0',
    databaseURL: 'https://project-f7aa0-default-rtdb.firebaseio.com',
    storageBucket: 'project-f7aa0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGx7OUCshzzTZF2yC1jxOLnuxgS_V1EWc',
    appId: '1:417667239161:ios:0a9a992dc52fc11255e628',
    messagingSenderId: '417667239161',
    projectId: 'project-f7aa0',
    databaseURL: 'https://project-f7aa0-default-rtdb.firebaseio.com',
    storageBucket: 'project-f7aa0.appspot.com',
    iosClientId: '417667239161-2q5mg5dstq0kec1174k18m46ra3c2dnb.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGx7OUCshzzTZF2yC1jxOLnuxgS_V1EWc',
    appId: '1:417667239161:ios:0a9a992dc52fc11255e628',
    messagingSenderId: '417667239161',
    projectId: 'project-f7aa0',
    databaseURL: 'https://project-f7aa0-default-rtdb.firebaseio.com',
    storageBucket: 'project-f7aa0.appspot.com',
    iosClientId: '417667239161-2q5mg5dstq0kec1174k18m46ra3c2dnb.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
